In [1]:
import pandas as pd 
from evolvepro.src.metrics import metrics_calc_sing, enrichment_factor, apk, avg_rank, best_rank, top_recall, ndcg
from evolvepro.src.utils import load_dataset

**Ideal Case**

In [2]:
variant_dummy = ['A50G', 'E22F', 'D34K', 'C94F', 'L100V', 
                 'V35H', 'P90R', 'W78E', 'D42S', 'M1T']
activity_dummy = [1.5, 1.2, 0.9, 0.8, 0.7, 
                  0.6, 0.5, 0.4, 0.3, 0.1]
dummy_dict = {'variant': variant_dummy, 
                'activity': activity_dummy}
dummy_labels = pd.DataFrame(dummy_dict, columns=dummy_dict.keys())
print(dummy_labels)
dummy_labels.to_csv('/home/tigem/m.livero/Desktop/EvolvePro/GPR68/dummy_labels.csv', index=False)
dummy_ypred = [0.95, 0.90, 0.85, 0.80, 0.75,
            0.70, 0.65, 0.60, 0.55, 0.50]
dummy_round_dict = {'variant': variant_dummy,
                    'y_pred': dummy_ypred}
dummy_df_round = pd.DataFrame(dummy_round_dict, columns=dummy_round_dict.keys())
print(dummy_df_round)
dummy_df_round.to_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_round1.csv', index=False)

  variant  activity
0    A50G       1.5
1    E22F       1.2
2    D34K       0.9
3    C94F       0.8
4   L100V       0.7
5    V35H       0.6
6    P90R       0.5
7    W78E       0.4
8    D42S       0.3
9     M1T       0.1
  variant  y_pred
0    A50G    0.95
1    E22F    0.90
2    D34K    0.85
3    C94F    0.80
4   L100V    0.75
5    V35H    0.70
6    P90R    0.65
7    W78E    0.60
8    D42S    0.55
9     M1T    0.50

In [12]:
dummy_labels = '/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_labels.csv'
dummy_round = pd.read_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_round1.csv')
output = '/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_results.csv'
round_dummy = 'Round Dummy'
metrics_calc_sing(round_dummy, 
                  dummy_labels, 
                  dummy_round, 
                  output, 
                  threshold_hit=0.6, 
                  fraction=0.5, 
                  k=5)

  variant  y_pred  activity  true_rank  activity_binary
0    A50G    0.95       1.5          1                1
1    E22F    0.90       1.2          2                1
2    D34K    0.85       0.9          3                1
3    C94F    0.80       0.8          4                1
4   L100V    0.75       0.7          5                1
5    V35H    0.70       0.6          6                1
6    P90R    0.65       0.5          7                0
7    W78E    0.60       0.4          8                0
8    D42S    0.55       0.3          9                0
9     M1T    0.50       0.1         10                0

            Round Dummy
ef             1.666667
ap             1.000000
avg_rank       3.000000
best_rank      1.000000
top_recall     0.833333
ndcg           1.000000

**Worst Case**

In [ ]:
variant_dummyw = ['A50G', 'E22F', 'D34K', 'C94F', 'L100V', 
                 'V35H', 'P90R', 'W78E', 'D42S', 'M1T']
activity_dummyw = [1.5, 1.2, 0.9, 0.8, 0.7, 
                  0.6, 0.5, 0.4, 0.3, 0.1]
dummy_dictw = {'variant': variant_dummyw, 
                'activity': activity_dummyw}
dummy_labelsw = pd.DataFrame(dummy_dict, columns=dummy_dict.keys())
print(dummy_labelsw)
dummy_labelsw.to_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_labels_worst.csv', index=False)
dummy_ypredw = [0.50, 0.55, 0.60, 0.65, 0.70,
            0.75, 0.80, 0.85, 0.90, 0.95]
dummy_round_dictw = {'variant': variant_dummyw,
                    'y_pred': dummy_ypredw}
dummy_df_roundw = pd.DataFrame(dummy_round_dictw, columns=dummy_round_dictw.keys())
print(dummy_df_roundw)
dummy_df_roundw.to_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_round1_worst.csv', index=False)

  variant  activity
0    A50G       1.5
1    E22F       1.2
2    D34K       0.9
3    C94F       0.8
4   L100V       0.7
5    V35H       0.6
6    P90R       0.5
7    W78E       0.4
8    D42S       0.3
9     M1T       0.1
  variant  y_pred
0    A50G    0.50
1    E22F    0.55
2    D34K    0.60
3    C94F    0.65
4   L100V    0.70
5    V35H    0.75
6    P90R    0.80
7    W78E    0.85
8    D42S    0.90
9     M1T    0.95

In [13]:
dummy_labels = '/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_labels_worst.csv'
dummy_round = pd.read_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_round1_worst.csv')
output = '/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_results_worst.csv'
round_dummy = 'Round Dummy'
metrics_calc_sing(round_dummy, 
                  dummy_labels, 
                  dummy_round, 
                  output, 
                  threshold_hit=0.6, 
                  fraction=0.5, 
                  k=5)

  variant  y_pred  activity  true_rank  activity_binary
0     M1T    0.95       0.1         10                0
1    D42S    0.90       0.3          9                0
2    W78E    0.85       0.4          8                0
3    P90R    0.80       0.5          7                0
4    V35H    0.75       0.6          6                1
5   L100V    0.70       0.7          5                1
6    C94F    0.65       0.8          4                1
7    D34K    0.60       0.9          3                1
8    E22F    0.55       1.2          2                1
9    A50G    0.50       1.5          1                1

            Round Dummy
ef             0.333333
ap             0.040000
avg_rank       8.000000
best_rank      6.000000
top_recall     0.166667
ndcg           0.212010

**Near values**

In [2]:
variant_dummy_near = ['A50G', 'E22F', 'D34K', 'C94F', 'L100V', 
                 'V35H', 'P90R', 'W78E', 'D42S', 'M1T']
activity_dummy_near = [1.5, 1.2, 0.9, 0.8, 0.7, 
                  0.6, 0.5, 0.4, 0.3, 0.1]
dummy_dict_near = {'variant': variant_dummy_near, 
                'activity': activity_dummy_near}
dummy_labels_near = pd.DataFrame(dummy_dict_near, columns=dummy_dict_near.keys())
print(dummy_labels_near)
dummy_labels_near.to_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_labels_near.csv', index=False)
dummy_ypred_near = [0.90, 0.93, 0.85, 0.69, 0.68,
            0.65, 0.59, 0.55, 0.50, 0.45]
dummy_round_dict_near = {'variant': variant_dummy_near,
                    'y_pred': dummy_ypred_near}
dummy_df_round_near = pd.DataFrame(dummy_round_dict_near, columns=dummy_round_dict_near.keys())
print(dummy_df_round_near)
dummy_df_round_near.to_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_round1_near.csv', index=False)

  variant  activity
0    A50G       1.5
1    E22F       1.2
2    D34K       0.9
3    C94F       0.8
4   L100V       0.7
5    V35H       0.6
6    P90R       0.5
7    W78E       0.4
8    D42S       0.3
9     M1T       0.1
  variant  y_pred
0    A50G    0.90
1    E22F    0.93
2    D34K    0.85
3    C94F    0.69
4   L100V    0.68
5    V35H    0.65
6    P90R    0.59
7    W78E    0.55
8    D42S    0.50
9     M1T    0.45

In [3]:
dummy_labels = '/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_labels_near.csv'
dummy_round = pd.read_csv('/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_round1_near.csv')
output = '/home/tigem/m.livero/Desktop/EvolvePro/giacomelli/test_metrics/dummy_results_near.csv'
round_dummy = 'Round Dummy'
metrics_calc_sing(round_dummy, 
                  dummy_labels, 
                  dummy_round, 
                  output, 
                  threshold_hit=0.6, 
                  fraction=0.5, 
                  k=5)

  variant  y_pred  activity  true_rank  activity_binary
0    E22F    0.93       1.2          2                1
1    A50G    0.90       1.5          1                1
2    D34K    0.85       0.9          3                1
3    C94F    0.69       0.8          4                1
4   L100V    0.68       0.7          5                1
5    V35H    0.65       0.6          6                1
6    P90R    0.59       0.5          7                0
7    W78E    0.55       0.4          8                0
8    D42S    0.50       0.3          9                0
9     M1T    0.45       0.1         10                0
0    1.000000
1    0.785714
2    0.571429
3    0.500000
4    0.428571
5    0.357143
6    0.285714
7    0.214286
8    0.142857
9    0.000000
Name: activity, dtype: float64
2.1625771456576457
0    0.785714
1    1.000000
2    0.571429
3    0.500000
4    0.428571
5    0.357143
6    0.285714
7    0.214286
8    0.142857
9    0.000000
Name: activity, dtype: float64
2.083490664280101

            Round Dummy
ef             1.666667
ap             1.000000
avg_rank       3.000000
best_rank      1.000000
top_recall     0.833333
ndcg           0.963430